#!/bin/sh
set -eu

app_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)

if [ -n "${XDG_DATA_DIRS:-}" ]; then
    XDG_DATA_DIRS="$app_dir/usr/share:$XDG_DATA_DIRS"
else
    XDG_DATA_DIRS="$app_dir/usr/share:/usr/local/share:/usr/share"
fi
export XDG_DATA_DIRS

if [ -n "${LD_LIBRARY_PATH:-}" ]; then
    LD_LIBRARY_PATH="$app_dir/usr/lib:$LD_LIBRARY_PATH"
else
    LD_LIBRARY_PATH="$app_dir/usr/lib"
fi
export LD_LIBRARY_PATH

exec "$app_dir/usr/bin/sculpt-lite" "$@"
